# docker-compose.yml

version: "3.8"
services:
  backend:
    build:
      context: ./contact-list-api
    container_name: contact_backend
    volumes:
      - ./contact-list-api:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - contact_net
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: contact_manager
      DB_USERNAME: root
      DB_PASSWORD: root

  frontend:
    build:
      context: ./contact-list-frontend
    container_name: contact_frontend
    volumes:
      - ./contact-list-frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    depends_on:
      - backend
    networks:
      - contact_net

  mysql:
    image: mysql:8.0
    container_name: contact_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contact_manager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - contact_net

volumes:
  mysql_data:

networks:
  contact_net:
